global:
  evaluation_interval: 15s
  scrape_interval: 15s
rule_files:
- rules/*.yml
scrape_configs:
- job_name: moe-trainer
  metrics_path: /metrics
  scrape_interval: 10s
  static_configs:
  - targets:
    - moe-trainer:8000
- job_name: redis
  static_configs:
  - targets:
    - redis:6379
