server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Application logs
  - job_name: moe-lab-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: moe-lab
          __path__: /app/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            service: service
            component: component
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
          component:

  # Training logs
  - job_name: training-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: training
          __path__: /app/logs/training/*.log
    pipeline_stages:
      - json:
          expressions:
            epoch: epoch
            step: step
            loss: loss
            lr: learning_rate
            throughput: tokens_per_second
      - labels:
          epoch:
          step:

  # Container logs
  - job_name: container-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: containers
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: log

  # System logs
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\S+\s+\d+\s+\d+:\d+:\d+)\s+(?P<hostname>\S+)\s+(?P<service>\S+):\s+(?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: Jan _2 15:04:05
      - labels:
          hostname:
          service: