name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details below.
        
  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: This feature doesn't exist in current version
          required: true
        - label: This is not a bug report (use Bug Report template)
          required: true
          
  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Model Architecture
        - Training Infrastructure
        - Inference Optimization
        - Visualization/Analytics
        - CLI/Tools
        - Documentation
        - Performance
        - Other
    validations:
      required: true
      
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Brief summary of the proposed feature
      placeholder: One-line description of the feature...
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem this feature addresses...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Detailed description of the proposed feature
      placeholder: Describe your proposed solution...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Alternative solutions you've considered
      placeholder: Describe alternatives...
      
  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: How would this feature be used?
      render: python
      placeholder: |
        # Example usage
        from moe_lab import NewFeature
        
        feature = NewFeature()
        result = feature.do_something()
        
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking current work
        - Critical - Essential for project
    validations:
      required: true
      
  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to help implement this?
      options:
        - label: I can implement this feature
        - label: I can provide design input
        - label: I can help with testing
        - label: I can help with documentation
        
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the feature
      placeholder: Add any other context...