apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: moe-api-hpa
  namespace: moe-lab
  labels:
    app: moe-api
    component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: moe-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  # CPU utilization
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metric: requests per second
  - type: Pods
    pods:
      metric:
        name: requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: moe-gpu-hpa
  namespace: moe-lab
  labels:
    app: moe-gpu
    component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: moe-gpu
  minReplicas: 1
  maxReplicas: 5
  metrics:
  # GPU utilization (custom metric)
  - type: Pods
    pods:
      metric:
        name: gpu_utilization
      target:
        type: AverageValue
        averageValue: "80"
  # Inference queue length
  - type: Pods
    pods:
      metric:
        name: inference_queue_length
      target:
        type: AverageValue
        averageValue: "10"
  # Memory utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # Longer for GPU workloads
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
      selectPolicy: Max
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: moe-api-pdb
  namespace: moe-lab
  labels:
    app: moe-api
    component: availability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: moe-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: moe-gpu-pdb
  namespace: moe-lab
  labels:
    app: moe-gpu
    component: availability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: moe-gpu