apiVersion: v1
kind: Namespace
metadata:
  name: moe-lab
  labels:
    name: moe-lab
    version: v1.0.0
    component: ml-platform
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: moe-lab-quota
  namespace: moe-lab
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: moe-lab-limits
  namespace: moe-lab
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim