apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: moe-trainer
  name: moe-trainer-deployment
  namespace: moe-trainer-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moe-trainer
  template:
    metadata:
      labels:
        app: moe-trainer
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: moe-trainer-config
        image: moe-trainer-lab:latest
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        name: moe-trainer
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
          requests:
            cpu: 1000m
            memory: 2Gi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
