apiVersion: apps/v1
kind: Deployment
metadata:
  name: moe-trainer
  labels:
    app: moe-trainer
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moe-trainer
  template:
    metadata:
      labels:
        app: moe-trainer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: moe-trainer
      nodeSelector:
        accelerator: nvidia-tesla-v100
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      containers:
      - name: moe-trainer
        image: moe-trainer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: api
        - containerPort: 8080
          name: dashboard
        - containerPort: 9090
          name: metrics
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: CUDA_VISIBLE_DEVICES
          value: "0,1,2,3"
        - name: NCCL_DEBUG
          value: "WARN"
        - name: MODEL_CACHE_DIR
          value: "/app/models"
        - name: DATA_DIR
          value: "/app/data"
        - name: CHECKPOINT_DIR
          value: "/app/checkpoints"
        - name: LOG_LEVEL
          value: "INFO"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: PROMETHEUS_URL
          value: "http://prometheus-service:9090"
        resources:
          requests:
            memory: "16Gi"
            cpu: "4"
            nvidia.com/gpu: 4
          limits:
            memory: "32Gi"
            cpu: "8"
            nvidia.com/gpu: 4
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
          readOnly: true
        - name: model-volume
          mountPath: /app/models
        - name: checkpoint-volume
          mountPath: /app/checkpoints
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: moe-data-pvc
      - name: model-volume
        persistentVolumeClaim:
          claimName: moe-models-pvc
      - name: checkpoint-volume
        persistentVolumeClaim:
          claimName: moe-checkpoints-pvc
      - name: config-volume
        configMap:
          name: moe-trainer-config

---
apiVersion: v1
kind: Service
metadata:
  name: moe-trainer-service
  labels:
    app: moe-trainer
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    name: api
  - port: 8080
    targetPort: 8080
    name: dashboard
  - port: 9090
    targetPort: 9090
    name: metrics
  selector:
    app: moe-trainer

---
apiVersion: v1
kind: Service
metadata:
  name: moe-trainer-lb
  labels:
    app: moe-trainer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    name: api
  - port: 8080
    targetPort: 8080
    name: dashboard
  selector:
    app: moe-trainer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: moe-trainer-config
data:
  config.yaml: |
    model:
      vocab_size: 32000
      hidden_size: 4096
      num_experts: 64
      experts_per_token: 2
      num_layers: 32
      num_attention_heads: 32
      moe_layers: [4, 8, 12, 16, 20, 24, 28]
      aux_loss_coef: 0.01
      router_z_loss_coef: 0.001
      
    training:
      learning_rate: 3e-4
      per_device_train_batch_size: 2
      gradient_accumulation_steps: 8
      max_grad_norm: 1.0
      num_epochs: 10
      warmup_steps: 1000
      save_steps: 1000
      eval_steps: 500
      logging_steps: 100
      bf16: true
      dataloader_num_workers: 4
      
    data:
      max_seq_length: 2048
      data_cache_dir: "/app/data/cache"
      
    distributed:
      strategy: "expert_parallel"
      expert_parallel_size: 4
      
    optimization:
      enable_torch_compile: true
      compile_mode: "reduce-overhead"
      enable_mixed_precision: true
      precision_dtype: "bfloat16"
      enable_expert_batching: true
      expert_batch_size: 4096

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moe-data-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moe-models-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moe-checkpoints-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: moe-trainer
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: moe-trainer-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: moe-trainer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: moe-trainer-role
subjects:
- kind: ServiceAccount
  name: moe-trainer
  namespace: default

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: moe-trainer-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: moe-trainer
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: nvidia.com/gpu
      target:
        type: Utilization
        averageUtilization: 85